[package]
name = "fooster_lights"
version = "0.1.0"
authors = ["Lily Foster <lily@lily.flowers>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "^0.4"
rocket_contrib = { version = "^0.4", features = ["json", "tera_templates"] }
rosc = "^0.4"
rppal = { git = "https://github.com/golemparts/rppal.git" }
serde = { version = "^1.0", features = ["derive"] }
serde_with = "^1.6"
yansi = "^0.5"
